---
name: Quality Gates

on:
  push:
  pull_request:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  lint:
    needs: clone
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # - name: arduino-lint
      #   uses: arduino/arduino-lint-action@v1
      #   with:
      #     library-manager: update
      #     compliance: strict

      - uses: cpp-linter/cpp-linter-action@v2
        with:
          style: 'file'  # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          tidy-review: true # Enable clang suggestions in PRs
          files-changed-only: false
          version: 15 # PIO embeded clang version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
