---
name: Quality Gates

on:
  push:
  pull_request:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: arduino-lint
      #   uses: arduino/arduino-lint-action@v1
      #   with:
      #     library-manager: update
      #     compliance: strict

      - uses: cpp-linter/cpp-linter-action@v2
        with:
          style: llvm
          files-changed-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
