---
name: Quality Gates

on:
  push:
  pull_request:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: arduino-lint
      #   uses: arduino/arduino-lint-action@v1
      #   with:
      #     library-manager: update
      #     compliance: strict

      - name: Cache pio and pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: PIO Lint
        run: pio check --fail-on-defect=high --fail-on-defect=medium
